spring:
  application:
    name: GT-Parking
  datasource:
    url: jdbc:sqlserver://parkingsystem.c5s8024yq9iy.us-east-1.rds.amazonaws.com:1433;databaseName=ParkingSystem
    username: admin
    password: xxxxxx
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
server:
  # edit the port of the application here
  port: 8443
  ssl:
    key-store: classpath:SSL/dev.localhost.com.p12
    key-store-password: 20010304
    key-store-type: PKCS12
    key-password: 20010304